const types = {
    flags: {
        GET_ALL_FLAGS: 'GET_ALL_FLAGS',
        SET_ALL_FLAGS: 'SET_ALL_FLAGS',
    },
    user: {
        GET_USER_DATA: 'GET_USER_DATA',
        SET_USER_DATA: 'SET_USER_DATA',
        SET_USER_SIGNOUT: 'SET_USER_SIGNOUT',
        SET_LOGIN_ERROR: 'SET_LOGIN_ERROR',
        GET_USER_INFO: 'GET_USER_INFO',
        SET_USER_INFO: 'SET_USER_INFO',
        SET_GLOBAL_INFO: 'SET_GLOBAL_INFO',

    },
    appState: {
        SET_SIDEBAR_COLLAPSE: 'SET_SIDEBAR_COLLAPSE',
        SET_APP_THEME: 'SET_APP_THEME',
    },
    organization: {
        GET_ORGANIZATION_DATA: 'GET_ORGANIZATION_DATA',
        SET_ORGANIZATION_DATA: 'SET_ORGANIZATION_DATA',
    },
    project: {
        GET_PROJECT_DATA: 'GET_PROJECT_DATA',
        SET_PROJECT_DATA: 'SET_PROJECT_DATA',
        SET_PROJECT_ERROR: 'SET_PROJECT_ERROR',
        SET_PROJECT_LOADING: 'SET_PROJECT_LOADING',
        CLEAR_PROJECT_DATA: 'CLEAR_PROJECT_DATA',
    },
    brickContent: {
        SET_INIT_CREATE_CONTENT_FORM: 'SET_INIT_CREATE_CONTENT_FORM',
        UPDATE_STACK: 'UPDATE_STACK',
        SET_SELECTED_WIDGET_KEY: 'SET_SELECTED_WIDGET_KEY',
        UPDATE_CREATE_CONTENT_META_DATA: 'UPDATE_CREATE_CONTENT_META_DATA',
        GET_NATIVE_FIELDS: 'GET_NATIVE_FIELDS',
        SET_NATIVE_FIELDS: 'SET_NATIVE_FIELDS',
        CREATE_BRICKS: 'CREATE_BRICKS',
        SET_CREATE_BRICKS_RESPONSE_OBJ: 'SET_CREATE_BRICKS_RESPONSE_OBJ',
    },
    content: {
        FETCH_CONTENT_LIST: 'FETCH_CONTENT_LIST',
        STORE_CONTENT_LIST: 'STORE_CONTENT_LIST',
        SET_CONTENT_LIST_LOADING: 'SET_CONTENT_LIST_LOADING',
        SET_CONTENT_ERROR: 'SET_CONTENT_ERROR',
        CLEAR_CONTENT_DATA: 'CLEAR_CONTENT_DATA',
        FETCH_BRICK_DETAILS: 'FETCH_BRICK_DETAILS',
        STORE_BRICK_DETAILS: 'STORE_BRICK_DETAILS',
        EDIT_BRICK_CONTENT: 'EDIT_BRICK_CONTENT',
        STORE_UPDATED_BRICK_CONTENT: 'STORE_UPDATED_BRICK_CONTENT',
        SET_EDIT_BRICK_CONTENT_LOADING: 'SET_EDIT_BRICK_CONTENT_LOADING',
        STORE_BRICK_BASIC_DETAILS: 'STORE_BRICK_BASIC_DETAILS',
    },
};

export default types;
